# STG file generated by Workcraft 3 (Return of the Hazard), version 3.3.3
.model STG2VA_STM
.inputs in1 in2
.outputs out1 out2 out3 out4
.graph
in1+ out1+
in1+/1 out1-
in1- p0a
in1-/1 out4-
in2+ out3+/1
in2+/1 out3-
in2- p0a
in2-/1 out4-
out1+ out2+
out1+/1 out4+/1
out1- in1-/1
out2+ out3+
out2+/1 out1+/1
out2- in1+/1 in2+/1
out3+ out4+
out3+/1 out2+/1
out3- in2-/1
out4+ in1-
out4+/1 in2-
out4- p0aa
p0a out2-
p0aa in1+ in2+
.marking {p0aa}
.end
