# STG file generated by Workcraft 3 (Return of the Hazard), version 3.3.3
.model WAIT1
.inputs REQ_1V8 SIG_1V8
.outputs SAN_1V8
.dummy e
.graph
REQ_1V8+ e
REQ_1V8- SAN_1V8-
SAN_1V8+ REQ_1V8-
SAN_1V8- REQ_1V8+
SIG_1V8+ p0a
SIG_1V8- p0
e SAN_1V8+ p0a
p0 SIG_1V8+
p0a SIG_1V8- e
.marking {<SAN_1V8-,REQ_1V8+> p0}
.end
